### ISSUE TITLE
Integrate high school names into Streak from Club Leader Intake Form

### ISSUE THREAD

**Issue by kyleemile** [hackclub/frontend#7]
This is of high priority.

**Comment by zachlatta** [comment]
Done! Completed in 4c6164781b19f175d4b5982a7dcda0cbbedef159 and 2ca1b1aa558d7ef14d5d0cb907ce57b5a31ca5ea in this repo and c4e727fa0e0d094659ca4c4761d453fbf4aa62bb, e5481915f2fa928afa59c6c272a394fdf30682c9, 2a2801ebbe1121b66a2d79742e16ca7d1fc045b7, and 77186b75be558e69cb7b6e3312519564c694268c in hackclub/api. Live at https://new.hackclub.com/intake.
